
export const SHINOBI_IMAGES = {
  sections: {
    anime: '/images/web-img/img_anime.webp',
    comics: '/images/web-img/img_comics.webp',
    event: '/images/web-img/img_event.webp',
    game: '/images/web-img/img_game.webp',
    goods: '/images/web-img/img_goods-1.webp',
    news: '/images/web-img/img_news.webp',
    special: '/images/web-img/img_special.webp',
  },
  ornaments: {
    ornament1: '/images/web-img/ornament1.webp',
    ornament2: '/images/web-img/ornament2.webp',
    ornament3: '/images/web-img/ornament3.webp',
    ornament5: '/images/web-img/ornament5.webp',
  },
  ninjas: [
    '/images/ninja-assets/habib_kakashi.jpg',
    '/images/ninja-assets/habib_mighty_guy.jpg',
    '/images/ninja-assets/habib_naruto.jpg',
    '/images/ninja-assets/habib_sword.jpg',
    '/images/ninja-assets/habib_rock_lee.jpg',
    '/images/ninja-assets/habib_kiba.jpg',
    '/images/ninja-assets/habib_hinata.jpg',
    '/images/ninja-assets/habib_sai.jpg',
    '/images/ninja-assets/habib_asuma.jpg',
    '/images/ninja-assets/habib_shino.jpg',
    '/images/ninja-assets/habib_sakura.jpg',
    '/images/ninja-assets/habib_lady_tsunade.jpg',
    '/images/ninja-assets/habib_tenten.jpg',
    '/images/ninja-assets/habib_kurenai.jpg',
    '/images/ninja-assets/habib_joji.jpg',
    '/images/ninja-assets/abubakar_habib.jpg',
    '/images/ninja-assets/n1.jpeg',
    '/images/ninja-assets/n2.jpeg',
    '/images/ninja-assets/n3.jpeg',
    '/images/ninja-assets/n4.jpeg',
    '/images/ninja-assets/habib_team.jpg',
  ],
  hero: '/images/ninja-assets/profile.jpg',
  videoBg: '/images/web-img/team_background.mp4',
};
