
export const SHINOBI_IMAGES = {
  sections: {
    anime: '/assets/web-img/img_anime.webp',
    comics: '/assets/web-img/img_comics.webp',
    event: '/assets/web-img/img_event.webp',
    game: '/assets/web-img/img_game.webp',
    goods: '/assets/web-img/img_goods-1.webp',
    news: '/assets/web-img/img_news.webp',
    special: '/assets/web-img/img_special.webp',
  },
  ornaments: {
    ornament1: '/assets/web-img/ornament1.webp',
    ornament2: '/assets/web-img/ornament2.webp',
    ornament3: '/assets/web-img/ornament3.webp',
    ornament5: '/assets/web-img/ornament5.webp',
  },
  ninjas: [
    '/assets/ninja-assets/habib_kakashi.jpg',
    '/assets/ninja-assets/habib_mighty_guy.jpg',
    '/assets/ninja-assets/habib_naruto.jpg',
    '/assets/ninja-assets/habib_sword.jpg',
    '/assets/ninja-assets/habib_rock_lee.jpg',
    '/assets/ninja-assets/habib_kiba.jpg',
    '/assets/ninja-assets/habib_hinata.jpg',
    '/assets/ninja-assets/habib_sai.jpg',
    '/assets/ninja-assets/habib_asuma.jpg',
    '/assets/ninja-assets/habib_shino.jpg',
    '/assets/ninja-assets/habib_sakura.jpg',
    '/assets/ninja-assets/habib_lady_tsunade.jpg',
    '/assets/ninja-assets/habib_tenten.jpg',
    '/assets/ninja-assets/habib_kurenai.jpg',
    '/assets/ninja-assets/habib_joji.jpg',
    '/assets/ninja-assets/abubakar_habib.jpg',
    '/assets/ninja-assets/n1.jpeg',
    '/assets/ninja-assets/n2.jpeg',
    '/assets/ninja-assets/n3.jpeg',
    '/assets/ninja-assets/n4.jpeg',
    '/assets/ninja-assets/habib_team.jpg',
    '/assets/ninja-assets/habib_kakashi_1.jpg',
    '/assets/ninja-assets/wa_1.jpeg',
    '/assets/ninja-assets/wa_2.jpeg',
    '/assets/ninja-assets/wa_3.jpeg',
    '/assets/ninja-assets/wa_4.jpeg',
    '/assets/ninja-assets/wa_5.jpeg',
    '/assets/ninja-assets/wa_6.jpeg',
    '/assets/ninja-assets/wa_7.jpeg',
    '/assets/ninja-assets/wa_8.jpeg',
    '/assets/ninja-assets/wa_9.jpeg',
    '/assets/ninja-assets/wa_10.jpeg',
    '/assets/ninja-assets/wa_11.jpeg',
    '/assets/ninja-assets/wa_12.jpeg',
    '/assets/ninja-assets/wa_13.jpeg',
    '/assets/ninja-assets/wa_14.jpeg',
    '/assets/ninja-assets/wa_15.jpeg',
    '/assets/ninja-assets/wa_16.jpeg',
  ],
  hero: '/assets/ninja-assets/profile.jpg',
  videoBg: '/assets/web-img/team_background.mp4',
};
